// Note: image URLs sourced from Figma MCP assets (expire after 7 days — replace with permanent URLs)
const IMG_RIVER   = "https://www.figma.com/api/mcp/asset/06df01ee-0e71-4a47-8a54-cf89dc5cb542";
const IMG_FOREST  = "https://www.figma.com/api/mcp/asset/23d0e15c-a62d-4139-9790-d4998a803133";
const IMG_FALLS   = "https://www.figma.com/api/mcp/asset/50e143c1-6bd2-4ce8-972e-7cbeded6b2c6";

export const EXPERIENCES = [
  {
    id: 1,
    slug: "termas-tolhuaca",
    emoji: "♨️",
    image: IMG_FALLS,
    color: "#8B4513",
    bgColor: "#FDF0E8",
    type: "full",
    price: 65000,
    difficulty: "easy",
    minPax: 1,
    maxPax: 12,
    includes: { es: "Transporte, guía, almuerzo, acceso termas", en: "Transport, guide, lunch, thermal access" },
    name: { es: "Termas de Tolhuaca", en: "Tolhuaca Hot Springs" },
    desc: {
      es: "Un día de relajación total en las termas naturales del Parque Nacional Tolhuaca, rodeado de bosque nativo y montañas volcánicas.",
      en: "A full day of relaxation at the natural hot springs of Tolhuaca National Park, surrounded by native forest and volcanic mountains.",
    },
  },
  {
    id: 2,
    slug: "lonquimay",
    emoji: "🌋",
    image: IMG_FOREST,
    color: "#C0392B",
    bgColor: "#FDECEC",
    type: "full",
    price: 75000,
    difficulty: "hard",
    minPax: 2,
    maxPax: 8,
    includes: { es: "Guía certificado, equipo técnico, almuerzo", en: "Certified guide, technical gear, lunch" },
    name: { es: "Volcán Lonquimay", en: "Lonquimay Volcano" },
    desc: {
      es: "Trekking de altura hasta el cráter del volcán Lonquimay. Vistas panorámicas de la Cordillera de los Andes desde 2.865 msnm.",
      en: "High-altitude trekking to the crater of Lonquimay Volcano. Panoramic views of the Andes from 2,865 m above sea level.",
    },
  },
  {
    id: 3,
    slug: "bosque-araucarias",
    emoji: "🌲",
    image: IMG_RIVER,
    color: "#27AE60",
    bgColor: "#E8F8EF",
    type: "half",
    price: 32000,
    difficulty: "easy",
    minPax: 1,
    maxPax: 16,
    includes: { es: "Guía naturalista, snack, transporte local", en: "Naturalist guide, snack, local transport" },
    name: { es: "Bosque de araucarias", en: "Araucaria forest" },
    desc: {
      es: "Caminata interpretativa por el bosque milenario de araucarias, el árbol nacional de Chile, declarado Patrimonio de la Humanidad.",
      en: "Interpretive walk through the ancient araucaria forest — Chile's national tree and UNESCO World Heritage site.",
    },
  },
  {
    id: 4,
    slug: "kayak-biobio",
    emoji: "🛶",
    image: IMG_RIVER,
    color: "#2980B9",
    bgColor: "#EAF4FD",
    type: "half",
    price: 38000,
    difficulty: "medium",
    minPax: 2,
    maxPax: 10,
    includes: { es: "Kayak, chaleco salvavidas, guía, snack", en: "Kayak, life jacket, guide, snack" },
    name: { es: "Kayak río Cautín", en: "Cautín river kayak" },
    desc: {
      es: "Descenso en kayak por el río Cautín entre cascadas y vegetación nativa. Para todos los niveles.",
      en: "Kayak descent along the Cautín river among waterfalls and native vegetation. Suitable for all levels.",
    },
  },
  {
    id: 5,
    slug: "cabalgata",
    emoji: "🐴",
    image: IMG_FALLS,
    color: "#8E44AD",
    bgColor: "#F3EAF9",
    type: "half",
    price: 35000,
    difficulty: "easy",
    minPax: 2,
    maxPax: 8,
    includes: { es: "Caballo, guía arriero, poncho, mate", en: "Horse, gaucho guide, poncho, mate" },
    name: { es: "Cuesta Las Raíces", en: "Las Raíces Pass" },
    desc: {
      es: "Recorrido a caballo por la Cuesta Las Raíces con vistas al Lonquimay. Experiencia auténtica de la vida campestre patagónica.",
      en: "Horseback ride through Las Raíces Pass with views of Lonquimay. An authentic Patagonian ranch experience.",
    },
  },
  {
    id: 6,
    slug: "condor-birding",
    emoji: "🦅",
    image: IMG_FOREST,
    color: "#E67E22",
    bgColor: "#FEF3E6",
    type: "half",
    price: 28000,
    difficulty: "easy",
    minPax: 1,
    maxPax: 6,
    includes: { es: "Binoculares, guía ornitólogo, desayuno", en: "Binoculars, ornithologist guide, breakfast" },
    name: { es: "Salto El Tirinto", en: "El Tirinto Waterfall" },
    desc: {
      es: "Excursión al imponente salto El Tirinto, rodeado de bosque nativo. Un espectáculo natural único en la región.",
      en: "Excursion to the impressive El Tirinto waterfall, surrounded by native forest. A unique natural spectacle in the region.",
    },
  },
];