export const LANG = {
  es: {
    nav_experiences: "Experiencias",
    nav_mybooking: "Mi reserva",
    hero_title: "Malacahuello",
    hero_sub: "Experiencias únicas en el corazón de la Araucanía",
    hero_cta: "Ver experiencias",
    catalog_title: "Nuestras experiencias",
    filter_all: "Todas",
    filter_full: "Día completo",
    filter_half: "Medio día",
    full_day: "Día completo",
    half_day: "Medio día",
    half_day_hint: "Combina dos medios días para un día completo",
    add: "Agregar",
    added: "Agregada",
    unavailable: "No disponible",
    sidebar_title: "Tu reserva",
    sidebar_empty: "Aún no has seleccionado experiencias",
    sidebar_empty_sub: "Elige una experiencia del catálogo para comenzar",
    select_date: "Selecciona una fecha",
    select_am: "Mañana (AM)",
    select_pm: "Tarde (PM)",
    remove: "Quitar",
    total: "Total",
    checkout: "Ir al pago",
    combo_badge: "¡Combo día completo!",
    step_info: "Tus datos",
    step_pay: "Pago",
    step_confirm: "Confirmación",
    field_name: "Nombre completo",
    field_email: "Correo electrónico",
    field_phone: "Teléfono",
    field_pax: "Número de personas",
    field_notes: "Comentarios (opcional)",
    back: "Volver",
    continue: "Continuar",
    pay_with: "Pagar con",
    pay_mp: "Mercado Pago",
    pay_fintoc: "Fintoc (transferencia bancaria)",
    pay_disclaimer: "Serás redirigido al portal de pago seguro.",
    confirm_title: "¡Reserva confirmada!",
    confirm_sub: "Te enviaremos un correo con los detalles.",
    confirm_ref: "Número de reserva",
    confirm_back: "Volver al inicio",
    nights: "noches",
    per_person: "por persona",
    duration_full: "8 horas",
    duration_half: "4 horas",
    includes: "Incluye",
    difficulty: "Dificultad",
    diff_easy: "Fácil",
    diff_med: "Moderada",
    diff_hard: "Difícil",
    min_pax: "Mín. personas",
    max_pax: "Máx. personas",
    detail_close: "Cerrar",
    booking_summary: "Resumen de reserva",
    date_label: "Fecha",
    slot_label: "Horario",
    slot_full: "Día completo",
    slot_am: "Mañana",
    slot_pm: "Tarde",
    slot_unavailable: "No disponible este día",
    conflict_full: "Ya tienes una experiencia este día",
    conflict_am: "Ya tienes una experiencia esta mañana",
    conflict_pm: "Ya tienes una experiencia esta tarde",
    needs_slot: "Selecciona un horario",
    needs_date: "Selecciona una fecha",
    add_another_date: "Agregar otra fecha",
  },
  en: {
    nav_experiences: "Experiences",
    nav_mybooking: "My booking",
    hero_title: "Malacahuello",
    hero_sub: "Unique experiences in the heart of Araucanía",
    hero_cta: "Browse experiences",
    catalog_title: "Our experiences",
    filter_all: "All",
    filter_full: "Full day",
    filter_half: "Half day",
    full_day: "Full day",
    half_day: "Half day",
    half_day_hint: "Combine two half days into a full day",
    add: "Add",
    added: "Added",
    unavailable: "Unavailable",
    sidebar_title: "Your booking",
    sidebar_empty: "No experiences selected yet",
    sidebar_empty_sub: "Choose an experience from the catalog to get started",
    select_date: "Select a date",
    select_am: "Morning (AM)",
    select_pm: "Afternoon (PM)",
    remove: "Remove",
    total: "Total",
    checkout: "Proceed to checkout",
    combo_badge: "Full day combo!",
    step_info: "Your details",
    step_pay: "Payment",
    step_confirm: "Confirmation",
    field_name: "Full name",
    field_email: "Email address",
    field_phone: "Phone number",
    field_pax: "Number of guests",
    field_notes: "Comments (optional)",
    back: "Back",
    continue: "Continue",
    pay_with: "Pay with",
    pay_mp: "Mercado Pago",
    pay_fintoc: "Fintoc (bank transfer)",
    pay_disclaimer: "You will be redirected to a secure payment portal.",
    confirm_title: "Booking confirmed!",
    confirm_sub: "We'll send you an email with all the details.",
    confirm_ref: "Booking reference",
    confirm_back: "Back to home",
    per_person: "per person",
    duration_full: "8 hours",
    duration_half: "4 hours",
    includes: "Includes",
    difficulty: "Difficulty",
    diff_easy: "Easy",
    diff_med: "Moderate",
    diff_hard: "Difficult",
    min_pax: "Min. guests",
    max_pax: "Max. guests",
    detail_close: "Close",
    booking_summary: "Booking summary",
    date_label: "Date",
    slot_label: "Time slot",
    slot_full: "Full day",
    slot_am: "Morning",
    slot_pm: "Afternoon",
    slot_unavailable: "Unavailable on this day",
    conflict_full: "Another experience already fills this day",
    conflict_am: "You already have a morning experience",
    conflict_pm: "You already have an afternoon experience",
    needs_slot: "Pick a time slot",
    needs_date: "Pick a date",
    add_another_date: "Add another date",
  },
};